configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/association.smk"
include: "rules/count.smk"
include: "rules/combine.smk"


wildcard_constraints:
    sample="|".join(list(samples["sample"])),


rule all:
    input:
        outputs,
